import { ArrowLeft, Box, Code2, KeyRound, LockKeyhole, Mail, ShieldCheck } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link, Navigate } from 'react-router-dom'
import { useAuth } from './auth'
import { isDesktopRuntime } from './runtime'

export default function AuthPage({ mode }: { mode: 'login' | 'register' | 'reset' }) {
  const auth = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  if (auth.status === 'authenticated' || auth.status === 'offline') return <Navigate to="/app" replace />
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(''); try { if (mode === 'login') await auth.signIn(email, password); else if (mode === 'register') { await auth.signUp(email, password); setMessage('验证邮件已发送，请完成验证后登录。') } else { await auth.resetPassword(email); setMessage('密码重置邮件已发送。') } } catch (reason) { setMessage(reason instanceof Error ? reason.message : '操作失败') } finally { setBusy(false) } }
  const title = mode === 'login' ? '登录 Anpack' : mode === 'register' ? '创建免费账号' : '重置密码'
  return <main className="auth-page"><div className="auth-art"><Link className="site-brand" to="/"><span><Box size={18}/></span><b>Anpack</b><i>PACKAGING STUDIO</i></Link><div className="auth-art-copy"><div className="eyebrow"><span/>LOCAL PROJECTS. VERIFIED ACCESS.</div><h1>你的包装项目，<br/>始终留在本机。</h1><p>登录只验证使用权限。Anpack 不会把项目、模型或包装图案上传到账号服务。</p></div><div className="auth-dieline"><svg viewBox="0 0 500 340"><g fill="none" stroke="#ff7a22" strokeWidth="2"><path d="M30 100h95v150H30zM125 100h140v150H125zM265 100h95v150h-95zM360 100h110v150H360zM125 45h140v55H125zM125 250h140v55H125z"/></g><g stroke="#69717d" strokeDasharray="6 6"><path d="M30 100h440M30 250h440M125 45v260M265 45v260M360 100v150"/></g></svg><span>ANPACK / LOCAL-FIRST / GLB</span></div></div><section className="auth-panel"><Link className="auth-back" to="/"><ArrowLeft size={15}/>{isDesktopRuntime ? '返回' : '返回官网'}</Link><div className="auth-form-wrap"><span className="auth-symbol">{mode === 'reset' ? <KeyRound size={23}/> : <LockKeyhole size={23}/>}</span><h2>{title}</h2><p>{mode === 'login' ? '使用同一账号进入网页版和桌面版。' : mode === 'register' ? '所有功能开放使用，不设置付费等级。' : '输入注册邮箱接收安全重置链接。'}</p>{!auth.configured && <div className="auth-config-warning"><ShieldCheck size={16}/><span>尚未配置 Supabase。请根据 <code>.env.example</code> 填写项目地址和匿名密钥。</span></div>}<form onSubmit={submit}><label><span>邮箱</span><div><Mail size={15}/><input required type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="name@example.com" /></div></label>{mode !== 'reset' && <label><span>密码</span><div><KeyRound size={15}/><input required minLength={8} type="password" autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={event=>setPassword(event.target.value)} placeholder="至少 8 位字符" /></div></label>}{mode==='login' && <Link className="forgot" to="/reset-password">忘记密码？</Link>}<button className="auth-submit" disabled={busy || !auth.configured}>{busy ? '正在处理…' : mode==='login'?'登录工作台':mode==='register'?'创建账号':'发送重置邮件'}</button></form>{mode!=='reset' && <><div className="auth-divider"><span>或</span></div><button className="github-auth" disabled={busy || !auth.configured} onClick={()=>void auth.signInWithGitHub().catch(reason=>setMessage(reason instanceof Error?reason.message:'GitHub登录失败'))}><Code2 size={17}/>使用 GitHub 登录</button></>}{message && <div className="auth-message" role="status">{message}</div>}<div className="auth-switch">{mode==='login'?<>没有账号？<Link to="/register">免费注册</Link></>:mode==='register'?<>已有账号？<Link to="/login">立即登录</Link></>:<Link to="/login">返回登录</Link>}</div></div><footer><LockKeyhole size={13}/>本地项目 · 加密会话 · 30天桌面离线授权</footer></section></main>
}
