import { ArrowRight, Box, Check, Cpu, Download, FileBox, Code2, Layers3, LockKeyhole, MonitorUp, PackageOpen, PenTool, ScanLine, Sparkles, WandSparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useEffect, useState } from 'react'
import SiteHeader from './SiteHeader'
import { appVersion, repositoryUrl } from './runtime'

interface ReleaseManifest { version: string; publishedAt: string; installer: { url: string; size: string; sha256: string }; portable?: { url: string; size: string; sha256: string } }

const features = [
  [PenTool, '包装展开设计', '外侧与内侧、多面图案、出血线、粘合舌以及参数尺寸实时同步。'],
  [Layers3, '网页网格建模', '对象、顶点、边、面选择，支持挤出、内插、倒角、UV与通用格式导入。'],
  [Sparkles, '写实商品场景', 'PBR材质、HDR环境、灯光预设、自动构图以及最高4K静态输出。'],
  [Cpu, '本地 Cycles', '桌面版调用内置 Blender Cycles，自动选择显卡并回退CPU，不上传产品资产。'],
] as const

export default function MarketingPage() {
  const [release, setRelease] = useState<ReleaseManifest | null>(null)
  useEffect(() => { fetch(`${import.meta.env.BASE_URL}release-manifest.json`).then(response => response.ok ? response.json() : null).then(setRelease).catch(() => null) }, [])
  return <div className="site-shell"><SiteHeader /><main>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span />LOCAL-FIRST PACKAGING WORKFLOW</div><h1>从展开设计到<br /><em>最终渲染</em>，一套完成。</h1><p>Anpack 把包装结构、图案适配、3D建模与商品摄影场景放进同一个本地工作流。网页版随时编辑，桌面版使用 Blender Cycles 完成最终出图。</p><div className="hero-actions"><Link className="site-primary large" to="/login">登录网页版<ArrowRight size={17} /></Link><a className="site-secondary large" href="#desktop"><Download size={17} />下载 Windows 版</a></div><div className="hero-trust"><span><LockKeyhole size={14} />项目文件不上传</span><span><Check size={14} />无功能订阅</span><span><Code2 size={14} />GitHub公开发布</span></div></div>
      <div className="hero-visual" aria-label="Anpack 包装工作流预览"><div className="visual-grid" /><div className="dieline-card"><header><span>2D DIELINE</span><b>120 × 160 × 60 mm</b></header><svg viewBox="0 0 480 330" role="img" aria-label="包装展开结构"><g fill="none" stroke="#ff7a22" strokeWidth="2"><path d="M65 95h80v140H65zM145 95h120v140H145zM265 95h80v140h-80zM345 95h120v140H345z"/><path d="M145 35h120v60H145zM145 235h120v60H145zM65 55q40-38 80 0v40H65zM265 55q40-38 80 0v40h-80z"/></g><g stroke="#87909d" strokeDasharray="6 6"><path d="M65 95h400M65 235h400M145 35v260M265 35v260M345 55v180"/></g><rect x="157" y="108" width="96" height="114" rx="4" fill="#ff7a22" opacity=".16"/><text x="205" y="168" textAnchor="middle" fill="#ffb17d" fontSize="14">FRONT</text></svg></div><div className="render-card"><span className="render-light one"/><span className="render-light two"/><div className="product-box"><i>ANPACK</i><b>FIELD<br/>NOTES</b><small>PACKAGING OBJECT / 01</small></div><div className="render-floor"/><footer><span><i/> CYCLES READY</span><b>256 SAMPLES</b></footer></div><div className="visual-badge"><WandSparkles size={16} /><span>2D → 3D → CYCLES</span></div></div>
    </section>
    <section className="metrics"><div><b>13+</b><span>纸盒可编辑印刷面</span></div><div><b>4K</b><span>本地静态效果图</span></div><div><b>GLB</b><span>统一内部模型格式</span></div><div><b>0</b><span>强制订阅节点</span></div></section>
    <section className="workflow-section" id="workflow"><div className="section-kicker">ONE CONTINUOUS FLOW</div><div className="section-heading"><h2>设计过程不断线</h2><p>尺寸、图案、材质和场景保留在同一个 Anpack 项目中，无需在多个在线服务之间上传转换。</p></div><div className="workflow-grid">{([[ScanLine,'01','选择或导入结构','使用包装结构库、绘制异形刀模或导入 DXF。'],[PackageOpen,'02','配置每一个印刷面','编辑外侧、内侧、插舌、粘合处和多材质槽。'],[FileBox,'03','实时检查三维结果','网页端 Three.js PBR 预览与2D修改同步更新。'],[MonitorUp,'04','生成最终商品图','网页GPU路径追踪，或桌面Cycles离线渲染。']] as const).map(([Icon,no,title,text])=><article key={no}><span>{no}</span><Icon size={24}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="feature-section" id="features"><div className="feature-title"><div className="section-kicker">BUILT FOR PACKAGING</div><h2>不是普通的3D查看器</h2></div><div className="feature-list">{features.map(([Icon,title,text],index)=><article key={title}><span>0{index+1}</span><Icon size={22}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section className="desktop-section" id="desktop"><div className="desktop-copy"><div className="section-kicker">WINDOWS DESKTOP</div><h2>把 Blender Cycles<br/>藏进一个简单按钮。</h2><p>桌面版内置 Blender 4.5 LTS 便携运行时。Anpack 自动传递 GLB、相机、灯光与输出配置，并解析渲染进度。</p><ul><li><Check size={15}/>OptiX、CUDA、HIP、oneAPI 与 CPU 自动回退</li><li><Check size={15}/>草稿、影棚、极致三档质量</li><li><Check size={15}/>透明背景、降噪、1K–4K与自定义保存位置</li></ul></div><div className="download-panel"><span className="download-icon"><Download size={27}/></span><div><small>LATEST WINDOWS X64</small><h3>Anpack {release?.version ?? appVersion}</h3><p>{release ? `${release.installer.size} · NSIS 安装程序` : 'GitHub Releases 构建准备中'}</p></div>{release ? <a className="site-primary large" href={release.installer.url}>下载安装包<ArrowRight size={16}/></a> : <a className="site-primary large" href={`${repositoryUrl}/releases`}>查看 Releases<ArrowRight size={16}/></a>}<dl><div><dt>系统</dt><dd>Windows 10/11 x64</dd></div><div><dt>签名</dt><dd>Updater 完整性签名</dd></div><div><dt>SHA-256</dt><dd>{release?.installer.sha256?.slice(0,20) ?? '发布后生成'}…</dd></div></dl><p className="smartscreen">首版安装程序未购买商业代码签名证书，Windows 可能显示 SmartScreen 提示。请仅从本官网或官方 GitHub Releases 下载并核对哈希。</p></div></section>
    <section className="faq-section" id="faq"><div><div className="section-kicker">QUESTIONS</div><h2>常见问题</h2></div><div className="faq-list">{[['真的完全免费吗？','编辑器、桌面程序与本地渲染不设置功能订阅。账号服务使用 Supabase 免费层，超过免费额度时可能需要限流、自建或付费。'],['网页版为什么也必须登录？','登录用于统一网页与桌面的身份入口。项目文件、模型和贴图仍只保存在你的浏览器或电脑中。'],['桌面版需要另外安装 Blender 吗？','不需要。Windows 安装包内置官方 Blender 4.5 LTS 运行时，并保留完整 GPL 许可信息。'],['支持哪些模型文件？','支持 GLB、glTF、FBX、OBJ与相关依赖文件；C4D和Blend工程建议先导出GLB。']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  </main><footer className="site-footer"><div className="site-brand"><span><Box size={17}/></span><b>Anpack</b></div><p>Local-first packaging design and rendering studio.</p><nav><Link to="/privacy">隐私说明</Link><Link to="/licenses">软件许可</Link><a href={repositoryUrl}>GitHub</a><Link to="/login">登录</Link></nav><small>© {new Date().getFullYear()} Anpack. All rights reserved.</small></footer></div>
}
